### ISSUE TITLE
Crash w/ Double Slabs Mod

### ISSUE THREAD

**Issue by WenXin20** [LordGrimmauld/windowlogging#1]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Windowlogging v0.0.1`
[`Double Slabs v2.11.7`](https://www.curseforge.com/minecraft/mc-mods/double-slabs)

If I add the `doubleslabs:vertical_slab` to the windowable tag, I will be able to combine a glass pane with the vertical slabs, but the vertical slab will then have a missing texture. If I then break the glass pane, the vertical slab changes to an Air Vertical Slab, which can crash the game. Is proper compatibility possible?
[Crash Report](https://gist.github.com/WenXin20/aeaa85d3f2760fc4c836a7a226e524de)

**Comment by LordGrimmauld** [comment]
I need to save the windowlogged blocks NBT. That would fix similar issues with "Snow! Real magic" where windowlogged slabs/walls/stairs default to accacia. As for the rendering with a missing texture, i will try to fix it, though that might be more difficult.
There is a reason why i did not put vertical slabs in the default config. I will try to fix it, we will see how successful i am with that.

**Comment by WenXin20** [comment]
Thanks for looking into this!

**Comment by LordGrimmauld** [comment]
Ok, this issue should be fixed in the new 1.15.2 release at https://www.curseforge.com/minecraft/mc-mods/windowlogging/files/3060621
However, i could not figure out how to fix it on 1.16, as something behaves differently there.

**Comment by WenXin20** [comment]
Thanks, I'll give it a try soon. Does this release also fix windowlogged fences not connecting?

**Comment by WenXin20** [comment]
No more crashes, and the slab displays properly, but if I mine the vertical slab while it is windowlogged, it won't drop anything and doesn't make a breaking sound.

**Comment by LordGrimmauld** [comment]
hmm, ok. That with the sound i have no idea how to fix, in theory it should just work.
That part with the drops is interesting, i might have to look further into that. For now, i am happy i got the crash and rendering fixed.

**Comment by Spiderach** [comment]
[crash-2023-08-03_01.20.58-client.txt](https://github.com/LordGrimmauld/windowlogging/files/12268477/crash-2023-08-03_01.20.58-client.txt)
It appears that this bug may have returned as of 1.18.2. Rendering on Double Slab's vertical slabs fails if they're windowlogged, and it can cause client crashes again.
