### ISSUE TITLE
[Request] Support for vertical planks from Quark and others

### ISSUE THREAD

**Issue by chimericdream** [LordGrimmauld/windowlogging#17]
Just what the title says. I love the ability to have glass panes in slabs, stairs, etc. It would be awesome if you could add support for vertical slabs like the horizontal ones.

**Comment by LordGrimmauld** [comment]
Vertical plank support should be added ever since quark tagged their planks, which is already a thing for a while. I also added the crystal panes and gold bars as valid windows
