### ISSUE TITLE
1.18: reloading world causes window-logged blocks to become invisible

### ISSUE THREAD

**Issue by RiverC** [LordGrimmauld/windowlogging#18]
Forge: 38.0.15
Windowlogging: mc1.18_v0.0.5

Test: Create a world in creative, log a glass pane in a wood slab (can be any kind of wood)

Save world and quit to menu.

Reload world, windowlogged block is completely invisible, but you can't place another block there, so it's clearly still there but simply not being rendered.

You can fix this by using a setblock command to air on that block, if you choose 'destroy' it will pop the slab off, showing that it's sitll there (you don't get the pane back for obvious reasons.)

**Comment by LordGrimmauld** [comment]
The fix is uploaded to curseforge as 0.0.6 and available soon at [https://www.curseforge.com/minecraft/mc-mods/windowlogging/files/3551341](https://www.curseforge.com/minecraft/mc-mods/windowlogging/files/3551341), currently awaiting curseforge approval
