### ISSUE TITLE
Server Crash java.lang.NoSuchFieldError: modelData

### ISSUE THREAD

**Issue by Mowmaster** [LordGrimmauld/windowlogging#19]
Server Crash with windowlogging-mc1.18_v0.0.
[crash-2021-12-08_04.53.28-server.txt](https://github.com/LordGrimmauld/windowlogging/files/7673468/crash-2021-12-08_04.53.28-server.txt)

I added support for it in Dust: https://github.com/Mowmaster/Dust/blob/1.18/src/main/resources/data/windowlogging/tags/blocks/windowable.json

BUT just to verify I placed a glass pane on a oak slab and got the same crash.

Any chance its a client method being called by the server somehow?

**Comment by LordGrimmauld** [comment]
https://www.curseforge.com/minecraft/mc-mods/windowlogging/files/3554797
This *should* fix his type of crash. I am not quite sure why it occured in the first place, but i did some cleanup aiming at resolving these.
