### ISSUE TITLE
Dupe bug with Block Carpentry

### ISSUE THREAD

**Issue by WenXin20** [LordGrimmauld/windowlogging#3]
`Minecraft v1.15.2`
`Forge v31.2.36`
`Windowlogging v0.0.1`
[`Block Carpentry v0.7.2`](https://www.curseforge.com/minecraft/mc-mods/blockcarpentry)

The Frame & Illusion Fences from Block Carpentry can be right-clicked with any block to take a new texture, but if it is windowlogged, the block will drop and then if the fence is broken, the block is dropped a second time, so basically infinite blocks.

**Comment by LordGrimmauld** [comment]
I can't reproduce this anymore, in my testing the block gets windowloged and doesn't take on issusion properties
