### ISSUE TITLE
No Transparency on Windowlogged Panes when using Embeddium (1.19.2, 0.1.1)

### ISSUE THREAD

**Issue by CamKablam** [LordGrimmauld/windowlogging#31]
Title is self explanatory
![image](https://github.com/LordGrimmauld/windowlogging/assets/47013387/87fb5140-2a1e-49a2-babb-3e23b7d4d472)
Here is my modlist, incase one of them is the problem
[Create Pals Dev.txt](https://github.com/user-attachments/files/15847775/Create.Pals.Dev.txt)

**Comment by Gavin456b** [comment]
Also have this issue for vanilla dyed glass

**Comment by CamKablam** [comment]
Nevermind, I've found the culprit.
It turns out it's Sodium, (or the forge port, embeddium)
This is an issue with Sodium has with transparency frequently.
