### ISSUE TITLE
Suggestion: relocate the 'windows' for the mod to a seperate tag

### ISSUE THREAD

**Issue by jsburger** [LordGrimmauld/windowlogging#4]
Something like #windowlogging:windows would do fine. This would be ideal for adding things that aren't glass panes, such as iron bars, without having to give them the inaccurate tag of #forge:glass_panes. The windows tag would only need to include glass_panes by default, as the intent is just to open up the system.

**Comment by LordGrimmauld** [comment]
Done in 9ab4a443ab5e074da000a1ccd359994bb7289df9
