### ISSUE TITLE
[Suggestion] Add windowlogging to trapdoors

### ISSUE THREAD

**Issue by SamL2020** [LordGrimmauld/windowlogging#8]
This would be a very nice feature to have, so we can create windows like this:
![example](https://media.discordapp.net/attachments/801580286264606750/805237299922468864/unknown.png)

**Comment by LordGrimmauld** [comment]
I agree, its an option for marvelous builds. But people would assume trapdoors still working as trapdoors and such, adding that as an official feature has too many issues in my oppinion. You can however tag trapdoors as windowlogging:windowable to achieve this
